version: '2'
services:
  # db:
  #   image: mysql:8.0.15
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: pass
  #     MYSQL_DATABASE: database
  db:
    image: postgres:9.6-alpine
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/postgresql/data
      - ./db/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_ROOT_PASSWORD: root
      - POSTGRES_USER: user
      - POSTGRES_PASSWORD: pass
      - POSTGRES_DB: database
volumes:
  db:
    external: false
