version: '3'
services:
  # db:
  #   image: mysql:8.0.15
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: pass
  #     MYSQL_DATABASE: database
  db:
    image: postgres:9.6-alpine # docs https://hub.docker.com/_/postgres
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/postgres:/docker-entrypoint-initdb.d
    env_file: ./development.env
volumes:
  db:
    external: false
